---
# defaults file for postgresql

postgresql__version: 14
postgresql__extensions: []
postgresql__global_config_options: []
# postgresql__includeconf:
# postgresql__hba_entries:
postgresql__databases: 
  - {name: testdb,
    lc_collate: 'en_US.UTF-8',
    lc_ctype: 'en_US.UTF-8',
    encoding: 'UTF-8',
    template: 'template0',
    owner: postgres,
    extension: [], # check that you have installed then needed extension module before
    state: 'present'
   }

postgresql__users:
  - {name: "db_user",
    password: "supersecure",
    encrypted: yes,
    expires: 'infinity',
    state: 'present',
    conn_limit: none,
    priv: none,
    role_attr_flags: none,
    db: testdb
}

postgresql__install_pgbackrest: false
postgresql__install_pg_auto_failover: false
postgresql__disable_initdb: false
